//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/location/LocationRetriever.java
//

#include "J2ObjC_source.h"
#include "LocationRetriever.h"
#include "Stop.h"

@interface ComRemulasceLametroappJava_coreLocationLocationRetriever : NSObject
@end

@implementation ComRemulasceLametroappJava_coreLocationLocationRetriever

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getCurrentDistanceToStopWithComRemulasceLametroappJava_coreBasic_typesStop:", "getCurrentDistanceToStop", "D", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreLocationLocationRetriever = { 2, "LocationRetriever", "com.remulasce.lametroapp.java_core.location", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreLocationLocationRetriever;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreLocationLocationRetriever)
