//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/network_status/NetworkStatusReporter.java
//

#include "J2ObjC_source.h"
#include "NetworkStatusReporter.h"

@interface ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter : NSObject
@end

@implementation ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "reportFailure", NULL, "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter = { 2, "NetworkStatusReporter", "com.remulasce.lametroapp.java_core.network_status", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter)
