//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/types/RouteColor.java
//

#include "J2ObjC_source.h"
#include "RouteColor.h"

@implementation ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor

- (instancetype)initWithNSString:(NSString *)color {
  if (self = [super init]) {
    self->color_ = color;
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "RouteColor", NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "color_", NULL, 0x1, "Ljava.lang.String;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor = { 2, "RouteColor", "com.remulasce.lametroapp.java_core.static_data.types", NULL, 0x1, 1, methods, 1, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor)
