//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/types/RouteColor.java
//

#ifndef _ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor_H_
#define _ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor : NSObject < JavaIoSerializable > {
 @public
  NSString *color_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)color;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor)

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor, color_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor)

#endif // _ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor_H_
