//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/Route.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Route.h"
#include "RouteColor.h"

@interface ComRemulasceLametroappJava_coreBasic_typesRoute () {
 @public
  NSString *raw_;
  ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *color_;
}
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesRoute, raw_, NSString *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesRoute, color_, ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *)

@implementation ComRemulasceLametroappJava_coreBasic_typesRoute

- (instancetype)init {
  if (self = [super init]) {
    raw_ = @"";
  }
  return self;
}

- (instancetype)initWithNSString:(NSString *)route {
  if (self = [super init]) {
    raw_ = @"";
    raw_ = route;
  }
  return self;
}

- (instancetype)initWithNSString:(NSString *)route
withComRemulasceLametroappJava_coreStatic_dataTypesRouteColor:(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *)color {
  if (self = [super init]) {
    raw_ = @"";
    raw_ = route;
    self->color_ = color;
  }
  return self;
}

- (NSString *)getString {
  return raw_;
}

- (jboolean)isValid {
  return raw_ != nil && ![raw_ isEmpty];
}

- (void)setColorWithComRemulasceLametroappJava_coreStatic_dataTypesRouteColor:(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *)color {
  self->color_ = color;
}

- (ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *)getColor {
  return color_;
}

- (NSUInteger)hash {
  return ((jint) [((NSString *) nil_chk(raw_)) hash]);
}

- (jboolean)isEqual:(id)o {
  if ([nil_chk(o) getClass] != [self getClass]) {
    return NO;
  }
  return ((jint) [o hash]) == ((jint) [self hash]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Route", NULL, 0x1, NULL },
    { "initWithNSString:", "Route", NULL, 0x1, NULL },
    { "initWithNSString:withComRemulasceLametroappJava_coreStatic_dataTypesRouteColor:", "Route", NULL, 0x1, NULL },
    { "getString", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "isValid", NULL, "Z", 0x1, NULL },
    { "setColorWithComRemulasceLametroappJava_coreStatic_dataTypesRouteColor:", "setColor", "V", 0x1, NULL },
    { "getColor", NULL, "Lcom.remulasce.lametroapp.java_core.static_data.types.RouteColor;", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, .constantValue.asLong = ComRemulasceLametroappJava_coreBasic_typesRoute_serialVersionUID },
    { "raw_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "color_", NULL, 0x2, "Lcom.remulasce.lametroapp.java_core.static_data.types.RouteColor;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreBasic_typesRoute = { 2, "Route", "com.remulasce.lametroapp.java_core.basic_types", NULL, 0x1, 9, methods, 3, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreBasic_typesRoute;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreBasic_typesRoute)
