//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/StopNameTranslator.java
//

#include "J2ObjC_source.h"
#include "StopNameTranslator.h"
#include "java/util/Collection.h"

@interface ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator : NSObject
@end

@implementation ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getStopNameWithNSString:", "getStopName", "Ljava.lang.String;", 0x401, NULL },
    { "getStopIDWithNSString:", "getStopID", "Ljava.util.Collection;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator = { 2, "StopNameTranslator", "com.remulasce.lametroapp.java_core.static_data", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator)
