//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Route.java
//

#ifndef _ComRemulasceLametroappBasic_typesRoute_H_
#define _ComRemulasceLametroappBasic_typesRoute_H_

@class ComRemulasceLametroappStatic_dataTypesRouteColor;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

#define ComRemulasceLametroappBasic_typesRoute_serialVersionUID -1330979643298664422LL

@interface ComRemulasceLametroappBasic_typesRoute : NSObject < JavaIoSerializable > {
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)route;

- (instancetype)initWithNSString:(NSString *)route
withComRemulasceLametroappStatic_dataTypesRouteColor:(ComRemulasceLametroappStatic_dataTypesRouteColor *)color;

- (jboolean)isEqual:(id)o;

- (ComRemulasceLametroappStatic_dataTypesRouteColor *)getColor;

- (NSString *)getString;

- (NSUInteger)hash;

- (jboolean)isValid;

- (void)setColorWithComRemulasceLametroappStatic_dataTypesRouteColor:(ComRemulasceLametroappStatic_dataTypesRouteColor *)color;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappBasic_typesRoute)

J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappBasic_typesRoute, serialVersionUID, jlong)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappBasic_typesRoute)

#endif // _ComRemulasceLametroappBasic_typesRoute_H_
