//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Route.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/remulasce/lametroapp/basic_types/Route.h"
#include "com/remulasce/lametroapp/static_data/types/RouteColor.h"

@interface ComRemulasceLametroappBasic_typesRoute () {
 @public
  NSString *raw_;
  ComRemulasceLametroappStatic_dataTypesRouteColor *color_;
}
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappBasic_typesRoute, raw_, NSString *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappBasic_typesRoute, color_, ComRemulasceLametroappStatic_dataTypesRouteColor *)

@implementation ComRemulasceLametroappBasic_typesRoute

- (instancetype)init {
  if (self = [super init]) {
    ComRemulasceLametroappBasic_typesRoute_set_raw_(self, @"");
  }
  return self;
}

- (instancetype)initWithNSString:(NSString *)route {
  if (self = [super init]) {
    ComRemulasceLametroappBasic_typesRoute_set_raw_(self, @"");
    ComRemulasceLametroappBasic_typesRoute_set_raw_(self, route);
  }
  return self;
}

- (instancetype)initWithNSString:(NSString *)route
withComRemulasceLametroappStatic_dataTypesRouteColor:(ComRemulasceLametroappStatic_dataTypesRouteColor *)color {
  if (self = [super init]) {
    ComRemulasceLametroappBasic_typesRoute_set_raw_(self, @"");
    ComRemulasceLametroappBasic_typesRoute_set_raw_(self, route);
    ComRemulasceLametroappBasic_typesRoute_set_color_(self, color);
  }
  return self;
}

- (NSString *)getString {
  return raw_;
}

- (jboolean)isValid {
  return raw_ != nil && ![raw_ isEmpty];
}

- (void)setColorWithComRemulasceLametroappStatic_dataTypesRouteColor:(ComRemulasceLametroappStatic_dataTypesRouteColor *)color {
  ComRemulasceLametroappBasic_typesRoute_set_color_(self, color);
}

- (ComRemulasceLametroappStatic_dataTypesRouteColor *)getColor {
  return color_;
}

- (NSUInteger)hash {
  return ((jint) [((NSString *) nil_chk(raw_)) hash]);
}

- (jboolean)isEqual:(id)o {
  if ([nil_chk(o) getClass] != [self getClass]) {
    return NO;
  }
  return ((jint) [o hash]) == ((jint) [self hash]);
}

- (void)dealloc {
  RELEASE_(raw_);
  RELEASE_(color_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Route", NULL, 0x1, NULL },
    { "initWithNSString:", "Route", NULL, 0x1, NULL },
    { "initWithNSString:withComRemulasceLametroappStatic_dataTypesRouteColor:", "Route", NULL, 0x1, NULL },
    { "getString", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "isValid", NULL, "Z", 0x1, NULL },
    { "setColorWithComRemulasceLametroappStatic_dataTypesRouteColor:", "setColor", "V", 0x1, NULL },
    { "getColor", NULL, "Lcom.remulasce.lametroapp.static_data.types.RouteColor;", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, .constantValue.asLong = ComRemulasceLametroappBasic_typesRoute_serialVersionUID },
    { "raw_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "color_", NULL, 0x2, "Lcom.remulasce.lametroapp.static_data.types.RouteColor;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappBasic_typesRoute = { 2, "Route", "com.remulasce.lametroapp.basic_types", NULL, 0x1, 9, methods, 3, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappBasic_typesRoute;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappBasic_typesRoute)
