//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/Arrival.java
//

#include "Arrival.h"
#include "Destination.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Route.h"
#include "Stop.h"
#include "Vehicle.h"
#include "java/lang/System.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesArrival () {
 @public
  jboolean isInScope__;
  jlong lastPrediction_;
  jlong lastUpdate_;
}
@end

@implementation ComRemulasceLametroappJava_coreDynamic_dataTypesArrival

- (instancetype)init {
  if (self = [super init]) {
    isInScope__ = NO;
    route_ = [[ComRemulasceLametroappJava_coreBasic_typesRoute alloc] init];
    destination_ = [[ComRemulasceLametroappJava_coreBasic_typesDestination alloc] init];
    stop_ = [[ComRemulasceLametroappJava_coreBasic_typesStop alloc] init];
    vehicle_ = [[ComRemulasceLametroappJava_coreBasic_typesVehicle alloc] init];
  }
  return self;
}

- (jfloat)getEstimatedArrivalSeconds {
  jfloat time_delta = (lastPrediction_ - JavaLangSystem_currentTimeMillis()) / 1000.0f;
  return time_delta;
}

- (void)setEstimatedArrivalSecondsWithFloat:(jfloat)secondsTillArrival {
  lastPrediction_ = JavaLangSystem_currentTimeMillis() + J2ObjCFpToInt((secondsTillArrival * 1000));
  lastUpdate_ = JavaLangSystem_currentTimeMillis();
}

- (void)setRouteWithComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)route {
  self->route_ = route;
}

- (void)setVehicleWithComRemulasceLametroappJava_coreBasic_typesVehicle:(ComRemulasceLametroappJava_coreBasic_typesVehicle *)veh {
  self->vehicle_ = veh;
}

- (jlong)getTimeSinceLastEstimation {
  return JavaLangSystem_currentTimeMillis() - lastUpdate_;
}

- (void)setDestinationWithComRemulasceLametroappJava_coreBasic_typesDestination:(ComRemulasceLametroappJava_coreBasic_typesDestination *)d {
  self->destination_ = d;
}

- (void)setStopWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop {
  if (![((ComRemulasceLametroappJava_coreBasic_typesStop *) nil_chk(stop)) isValid]) {
    return;
  }
  self->stop_ = stop;
}

- (ComRemulasceLametroappJava_coreBasic_typesRoute *)getRoute {
  return route_;
}

- (ComRemulasceLametroappJava_coreBasic_typesStop *)getStop {
  return stop_;
}

- (ComRemulasceLametroappJava_coreBasic_typesDestination *)getDirection {
  return destination_;
}

- (ComRemulasceLametroappJava_coreBasic_typesVehicle *)getVehicleNum {
  return vehicle_;
}

- (NSUInteger)hash {
  NSString *h = @"";
  if ([((ComRemulasceLametroappJava_coreBasic_typesRoute *) nil_chk(route_)) isValid]) h = JreStrcat("$$", h, [route_ getString]);
  if ([((ComRemulasceLametroappJava_coreBasic_typesDestination *) nil_chk(destination_)) isValid]) h = JreStrcat("$$", h, [destination_ getString]);
  if ([((ComRemulasceLametroappJava_coreBasic_typesStop *) nil_chk(stop_)) isValid]) h = JreStrcat("$$", h, [stop_ getString]);
  if ([((ComRemulasceLametroappJava_coreBasic_typesVehicle *) nil_chk(vehicle_)) isValid]) h = JreStrcat("$$", h, [vehicle_ getString]);
  return ((jint) [h hash]);
}

- (jboolean)isEqual:(id)o {
  if ([nil_chk(o) getClass] != [self getClass]) {
    return NO;
  }
  return ((jint) [o hash]) == ((jint) [self hash]);
}

- (void)setScopeWithBoolean:(jboolean)inScope {
  self->isInScope__ = inScope;
}

- (jboolean)isInScope {
  return isInScope__;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Arrival", NULL, 0x1, NULL },
    { "getEstimatedArrivalSeconds", NULL, "F", 0x1, NULL },
    { "setEstimatedArrivalSecondsWithFloat:", "setEstimatedArrivalSeconds", "V", 0x1, NULL },
    { "setRouteWithComRemulasceLametroappJava_coreBasic_typesRoute:", "setRoute", "V", 0x1, NULL },
    { "setVehicleWithComRemulasceLametroappJava_coreBasic_typesVehicle:", "setVehicle", "V", 0x1, NULL },
    { "getTimeSinceLastEstimation", NULL, "J", 0x1, NULL },
    { "setDestinationWithComRemulasceLametroappJava_coreBasic_typesDestination:", "setDestination", "V", 0x1, NULL },
    { "setStopWithComRemulasceLametroappJava_coreBasic_typesStop:", "setStop", "V", 0x1, NULL },
    { "getRoute", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.Route;", 0x1, NULL },
    { "getStop", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.Stop;", 0x1, NULL },
    { "getDirection", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.Destination;", 0x1, NULL },
    { "getVehicleNum", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.Vehicle;", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
    { "setScopeWithBoolean:", "setScope", "V", 0x1, NULL },
    { "isInScope", NULL, "Z", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "route_", NULL, 0x0, "Lcom.remulasce.lametroapp.java_core.basic_types.Route;", NULL,  },
    { "destination_", NULL, 0x0, "Lcom.remulasce.lametroapp.java_core.basic_types.Destination;", NULL,  },
    { "stop_", NULL, 0x0, "Lcom.remulasce.lametroapp.java_core.basic_types.Stop;", NULL,  },
    { "vehicle_", NULL, 0x0, "Lcom.remulasce.lametroapp.java_core.basic_types.Vehicle;", NULL,  },
    { "isInScope__", "isInScope", 0x2, "Z", NULL,  },
    { "lastPrediction_", NULL, 0x2, "J", NULL,  },
    { "lastUpdate_", NULL, 0x2, "J", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreDynamic_dataTypesArrival = { 2, "Arrival", "com.remulasce.lametroapp.java_core.dynamic_data.types", NULL, 0x1, 16, methods, 7, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreDynamic_dataTypesArrival;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreDynamic_dataTypesArrival)
