//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/BasicLocation.java
//

#ifndef _ComRemulasceLametroappJava_coreBasic_typesBasicLocation_H_
#define _ComRemulasceLametroappJava_coreBasic_typesBasicLocation_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface ComRemulasceLametroappJava_coreBasic_typesBasicLocation : NSObject < JavaIoSerializable > {
 @public
  jdouble latitude_;
  jdouble longitude_;
}

#pragma mark Public

- (instancetype)initWithDouble:(jdouble)latitude
                    withDouble:(jdouble)longitude;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreBasic_typesBasicLocation)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreBasic_typesBasicLocation)

#endif // _ComRemulasceLametroappJava_coreBasic_typesBasicLocation_H_
