//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/Destination.java
//

#ifndef _ComRemulasceLametroappJava_coreBasic_typesDestination_H_
#define _ComRemulasceLametroappJava_coreBasic_typesDestination_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

#define ComRemulasceLametroappJava_coreBasic_typesDestination_serialVersionUID 6069634261484767760LL

@interface ComRemulasceLametroappJava_coreBasic_typesDestination : NSObject < JavaIoSerializable > {
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)dest;

- (jboolean)isEqual:(id)o;

- (NSString *)getString;

- (NSUInteger)hash;

- (jboolean)isValid;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreBasic_typesDestination)

J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreBasic_typesDestination, serialVersionUID, jlong)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreBasic_typesDestination)

#endif // _ComRemulasceLametroappJava_coreBasic_typesDestination_H_
