//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/location/GlobalLocationProvider.java
//

#include "GlobalLocationProvider.h"
#include "J2ObjC_source.h"
#include "LocationRetriever.h"

@interface ComRemulasceLametroappJava_coreLocationGlobalLocationProvider () {
}
@end

@implementation ComRemulasceLametroappJava_coreLocationGlobalLocationProvider

id<ComRemulasceLametroappJava_coreLocationLocationRetriever> ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_retriever_ = nil;

+ (void)setRetrieverWithComRemulasceLametroappJava_coreLocationLocationRetriever:(id<ComRemulasceLametroappJava_coreLocationLocationRetriever>)r {
  ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_setRetrieverWithComRemulasceLametroappJava_coreLocationLocationRetriever_(r);
}

+ (id<ComRemulasceLametroappJava_coreLocationLocationRetriever>)getRetriever {
  return ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_getRetriever();
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setRetrieverWithComRemulasceLametroappJava_coreLocationLocationRetriever:", "setRetriever", "V", 0x9, NULL },
    { "getRetriever", NULL, "Lcom.remulasce.lametroapp.java_core.location.LocationRetriever;", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "retriever_", NULL, 0xa, "Lcom.remulasce.lametroapp.java_core.location.LocationRetriever;", &ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_retriever_,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreLocationGlobalLocationProvider = { 2, "GlobalLocationProvider", "com.remulasce.lametroapp.java_core.location", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreLocationGlobalLocationProvider;
}

@end

void ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_setRetrieverWithComRemulasceLametroappJava_coreLocationLocationRetriever_(id<ComRemulasceLametroappJava_coreLocationLocationRetriever> r) {
  ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_init();
  ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_retriever_ = r;
}

id<ComRemulasceLametroappJava_coreLocationLocationRetriever> ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_getRetriever() {
  ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_init();
  return ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_retriever_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreLocationGlobalLocationProvider)
