//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/HTTPGetter.java
//

#include "HTTPGetter.h"
#include "J2ObjC_source.h"
#include "Log.h"
#include "NetworkStatusReporter.h"
#include "java/io/BufferedInputStream.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/lang/Exception.h"
#include "java/net/HttpURLConnection.h"
#include "java/net/URL.h"
#include "java/net/URLConnection.h"

__attribute__((unused)) static NSString *ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_readStreamWithJavaIoInputStream_(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *self, JavaIoInputStream *is);

@interface ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter () {
}

- (NSString *)readStreamWithJavaIoInputStream:(JavaIoInputStream *)is;
@end

@implementation ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter

NSString * ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_TAG_ = @"HTTPGetter";
ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter * ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_;

+ (NSString *)getHTTPResponseWithNSString:(NSString *)message
withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter:(id<ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter>)reporter {
  return ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getHTTPResponseWithNSString_withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter_(message, reporter);
}

- (NSString *)readStreamWithJavaIoInputStream:(JavaIoInputStream *)is {
  return ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_readStreamWithJavaIoInputStream_(self, is);
}

- (NSString *)doGetHTTPResponseWithNSString:(NSString *)message
withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter:(id<ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter>)reporter {
  @try {
    JavaNetURL *url = [[JavaNetURL alloc] initWithNSString:message];
    JavaNetHttpURLConnection *urlConnection = (JavaNetHttpURLConnection *) check_class_cast([url openConnection], [JavaNetHttpURLConnection class]);
    NSString *response;
    JavaIoInputStream *in = [[JavaIoBufferedInputStream alloc] initWithJavaIoInputStream:[((JavaNetHttpURLConnection *) nil_chk(urlConnection)) getInputStream]];
    response = ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_readStreamWithJavaIoInputStream_(self, in);
    [urlConnection disconnect];
    ComRemulasceLametroappJava_coreAnalyticsLog_vWithNSString_withNSString_(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_TAG_, JreStrcat("$$", @"HTTP Response: ", response));
    return response;
  }
  @catch (JavaIoIOException *e) {
    return @"";
  }
  @catch (JavaLangException *e) {
    return nil;
  }
}

+ (void)setHTTPGetterWithComRemulasceLametroappJava_coreDynamic_dataHTTPGetter:(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *)set {
  ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_setHTTPGetterWithComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_(set);
}

+ (ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *)getHTTPGetter {
  return ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getHTTPGetter();
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getHTTPResponseWithNSString:withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter:", "getHTTPResponse", "Ljava.lang.String;", 0x9, NULL },
    { "readStreamWithJavaIoInputStream:", "readStream", "Ljava.lang.String;", 0x2, NULL },
    { "doGetHTTPResponseWithNSString:withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter:", "doGetHTTPResponse", "Ljava.lang.String;", 0x1, NULL },
    { "setHTTPGetterWithComRemulasceLametroappJava_coreDynamic_dataHTTPGetter:", "setHTTPGetter", "V", 0x9, NULL },
    { "getHTTPGetter", NULL, "Lcom.remulasce.lametroapp.java_core.dynamic_data.HTTPGetter;", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TAG_", NULL, 0x1a, "Ljava.lang.String;", &ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_TAG_,  },
    { "getter_", NULL, 0xa, "Lcom.remulasce.lametroapp.java_core.dynamic_data.HTTPGetter;", &ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter = { 2, "HTTPGetter", "com.remulasce.lametroapp.java_core.dynamic_data", NULL, 0x1, 6, methods, 2, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter;
}

@end

NSString *ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getHTTPResponseWithNSString_withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter_(NSString *message, id<ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter> reporter) {
  ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_init();
  return [((ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *) nil_chk(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getHTTPGetter())) doGetHTTPResponseWithNSString:message withComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter:reporter];
}

NSString *ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_readStreamWithJavaIoInputStream_(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *self, JavaIoInputStream *is) {
  @try {
    JavaIoByteArrayOutputStream *bo = [[JavaIoByteArrayOutputStream alloc] init];
    jint i = [((JavaIoInputStream *) nil_chk(is)) read];
    while (i != -1) {
      [bo writeWithInt:i];
      i = [is read];
    }
    return [bo description];
  }
  @catch (JavaIoIOException *e) {
    return @"";
  }
}

void ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_setHTTPGetterWithComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *set) {
  ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_init();
  ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_ = set;
}

ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter *ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getHTTPGetter() {
  ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_init();
  if (ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_ == nil) {
    ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_ = [[ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter alloc] init];
  }
  return ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter_getter_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreDynamic_dataHTTPGetter)
