//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/LaMetroUtil.java
//

#ifndef _ComRemulasceLametroappJava_coreLaMetroUtil_H_
#define _ComRemulasceLametroappJava_coreLaMetroUtil_H_

@class ComRemulasceLametroappJava_coreBasic_typesAgency;
@class ComRemulasceLametroappJava_coreBasic_typesDestination;
@class ComRemulasceLametroappJava_coreBasic_typesRoute;
@class ComRemulasceLametroappJava_coreBasic_typesStop;
@class ComRemulasceLametroappJava_coreBasic_typesVehicle;
@protocol ComRemulasceLametroappJava_coreStatic_dataRouteColorer;
@protocol ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator;
@protocol JavaUtilList;

#include "J2ObjC_header.h"

@interface ComRemulasceLametroappJava_coreLaMetroUtil : NSObject {
}

#pragma mark Public

- (instancetype)init;

+ (void)fillinAgencyAndStopIDWithJavaUtilList:(id<JavaUtilList>)arrivals
withComRemulasceLametroappJava_coreBasic_typesAgency:(ComRemulasceLametroappJava_coreBasic_typesAgency *)agency
                                 withNSString:(NSString *)stopID;

+ (jboolean)isValidRouteWithComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)route;

+ (jboolean)isValidStopWithNSString:(NSString *)stop;

+ (NSString *)makePredictionsRequestWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop
                                   withComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)route;

+ (id<JavaUtilList>)parseAllArrivalsWithNSString:(NSString *)response;

+ (NSString *)standaloneSecondsRemainderTimeWithInt:(jint)seconds;

+ (NSString *)standaloneTimeToDisplayWithInt:(jint)seconds;

+ (NSString *)timeToDisplayWithInt:(jint)seconds;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreLaMetroUtil)

FOUNDATION_EXPORT jboolean ComRemulasceLametroappJava_coreLaMetroUtil_isValidStopWithNSString_(NSString *stop);

FOUNDATION_EXPORT jboolean ComRemulasceLametroappJava_coreLaMetroUtil_isValidRouteWithComRemulasceLametroappJava_coreBasic_typesRoute_(ComRemulasceLametroappJava_coreBasic_typesRoute *route);

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_makePredictionsRequestWithComRemulasceLametroappJava_coreBasic_typesStop_withComRemulasceLametroappJava_coreBasic_typesRoute_(ComRemulasceLametroappJava_coreBasic_typesStop *stop, ComRemulasceLametroappJava_coreBasic_typesRoute *route);

FOUNDATION_EXPORT id<JavaUtilList> ComRemulasceLametroappJava_coreLaMetroUtil_parseAllArrivalsWithNSString_(NSString *response);

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_timeToDisplayWithInt_(jint seconds);

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_standaloneTimeToDisplayWithInt_(jint seconds);

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_standaloneSecondsRemainderTimeWithInt_(jint seconds);

FOUNDATION_EXPORT void ComRemulasceLametroappJava_coreLaMetroUtil_fillinAgencyAndStopIDWithJavaUtilList_withComRemulasceLametroappJava_coreBasic_typesAgency_withNSString_(id<JavaUtilList> arrivals, ComRemulasceLametroappJava_coreBasic_typesAgency *agency, NSString *stopID);

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_NEXTBUS_FEED_URL_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, NEXTBUS_FEED_URL_, NSString *)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_BART_FEED_URL_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, BART_FEED_URL_, NSString *)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_BART_API_KEY_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, BART_API_KEY_, NSString *)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreLaMetroUtil_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, TAG_, NSString *)

FOUNDATION_EXPORT id<ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator> ComRemulasceLametroappJava_coreLaMetroUtil_locationTranslator_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, locationTranslator_, id<ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator>)
J2OBJC_STATIC_FIELD_SETTER(ComRemulasceLametroappJava_coreLaMetroUtil, locationTranslator_, id<ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator>)

FOUNDATION_EXPORT id<ComRemulasceLametroappJava_coreStatic_dataRouteColorer> ComRemulasceLametroappJava_coreLaMetroUtil_routeColorer_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreLaMetroUtil, routeColorer_, id<ComRemulasceLametroappJava_coreStatic_dataRouteColorer>)
J2OBJC_STATIC_FIELD_SETTER(ComRemulasceLametroappJava_coreLaMetroUtil, routeColorer_, id<ComRemulasceLametroappJava_coreStatic_dataRouteColorer>)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreLaMetroUtil)

#endif // _ComRemulasceLametroappJava_coreLaMetroUtil_H_
