//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/location/LocationRetriever.java
//

#ifndef _ComRemulasceLametroappJava_coreLocationLocationRetriever_H_
#define _ComRemulasceLametroappJava_coreLocationLocationRetriever_H_

@class ComRemulasceLametroappJava_coreBasic_typesStop;

#include "J2ObjC_header.h"

@protocol ComRemulasceLametroappJava_coreLocationLocationRetriever < NSObject, JavaObject >

#pragma mark Public

- (jdouble)getCurrentDistanceToStopWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreLocationLocationRetriever)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreLocationLocationRetriever)

#endif // _ComRemulasceLametroappJava_coreLocationLocationRetriever_H_
