//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/MultiArrivalTrip.java
//

#ifndef _ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip_H_
#define _ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip_H_

@class ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival;

#include "J2ObjC_header.h"
#include "Trip.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip : ComRemulasceLametroappJava_coreDynamic_dataTypesTrip {
 @public
  ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival *parentArrival_;
}

#pragma mark Public

- (instancetype)initWithComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival:(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival *)parentArrival;

- (void)dismiss;

- (jboolean)isEqual:(id)obj;

- (jdouble)getCurrentDistanceToStop;

- (jfloat)getPriority;

- (NSUInteger)hash;

- (jboolean)isValid;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip)

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip, parentArrival_, ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival *)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip, TAG_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip)

#endif // _ComRemulasceLametroappJava_coreDynamic_dataTypesMultiArrivalTrip_H_
