//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/network_status/NetworkStatusReporter.java
//

#ifndef _ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter_H_
#define _ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter_H_

#include "J2ObjC_header.h"

@protocol ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter < NSObject, JavaObject >

#pragma mark Package-Private

- (void)reportFailure;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter)

#endif // _ComRemulasceLametroappJava_coreNetwork_statusNetworkStatusReporter_H_
