//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/RegionalizationHelper.java
//

#include "Agency.h"
#include "BasicLocation.h"
#include "FieldSaver.h"
#include "GlobalLocationProvider.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LocationRetriever.h"
#include "Log.h"
#include "RegionalizationHelper.h"
#include "java/lang/Boolean.h"
#include "java/lang/Exception.h"
#include "java/lang/System.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"

__attribute__((unused)) static void ComRemulasceLametroappJava_coreRegionalizationHelper_autodetectRegions(ComRemulasceLametroappJava_coreRegionalizationHelper *self);

@interface ComRemulasceLametroappJava_coreRegionalizationHelper () {
 @public
  id<JavaUtilCollection> installedAgencies_;
  id<JavaUtilCollection> activeAgencies_;
  jlong lastRegionUpdateTime_;
  jboolean autoDetect_;
}
- (instancetype)init;

- (void)autodetectRegions;
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreRegionalizationHelper, installedAgencies_, id<JavaUtilCollection>)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreRegionalizationHelper, activeAgencies_, id<JavaUtilCollection>)

BOOL ComRemulasceLametroappJava_coreRegionalizationHelper_initialized = NO;

@implementation ComRemulasceLametroappJava_coreRegionalizationHelper

ComRemulasceLametroappJava_coreRegionalizationHelper * ComRemulasceLametroappJava_coreRegionalizationHelper_instance_;
NSString * ComRemulasceLametroappJava_coreRegionalizationHelper_ACTIVE_REGIONS_ = @"active_regions";
NSString * ComRemulasceLametroappJava_coreRegionalizationHelper_AUTODETECT_REGIONS_ = @"autodetect_regions";
id<ComRemulasceLametroappComponentsPersistenceFieldSaver> ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_;
NSString * ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_ = @"RegionalizationHelper";

+ (void)setPersistenceWithComRemulasceLametroappComponentsPersistenceFieldSaver:(id<ComRemulasceLametroappComponentsPersistenceFieldSaver>)persistence {
  ComRemulasceLametroappJava_coreRegionalizationHelper_setPersistenceWithComRemulasceLametroappComponentsPersistenceFieldSaver_(persistence);
}

- (instancetype)init {
  if (self = [super init]) {
    installedAgencies_ = [[JavaUtilArrayList alloc] init];
    activeAgencies_ = [[JavaUtilArrayList alloc] init];
    lastRegionUpdateTime_ = 0;
    autoDetect_ = YES;
  }
  return self;
}

- (void)loadPersistedAgencies {
  if (ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ == nil) {
    ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"RegionalizationHelper tried to load persisted agencies, but there's no saver set");
    if (installedAgencies_ == nil || [installedAgencies_ size] == 0) {
      ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"No installed agencies, can't properly make default active agencies");
      activeAgencies_ = [[JavaUtilArrayList alloc] init];
      return;
    }
    [((id<JavaUtilCollection>) nil_chk(activeAgencies_)) addAllWithJavaUtilCollection:installedAgencies_];
  }
  else {
    id useAutoDetect = [ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ loadObjectWithNSString:ComRemulasceLametroappJava_coreRegionalizationHelper_AUTODETECT_REGIONS_];
    if (useAutoDetect != nil && [useAutoDetect isKindOfClass:[JavaLangBoolean class]]) {
      @try {
        autoDetect_ = [(JavaLangBoolean *) check_class_cast(useAutoDetect, [JavaLangBoolean class]) booleanValue];
      }
      @catch (JavaLangException *e) {
        ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"Error loading persisted file, dropping it");
        [ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ saveObjectWithNSString:ComRemulasceLametroappJava_coreRegionalizationHelper_AUTODETECT_REGIONS_ withId:nil];
      }
    }
    id persistedDeal = [ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ loadObjectWithNSString:ComRemulasceLametroappJava_coreRegionalizationHelper_ACTIVE_REGIONS_];
    if (persistedDeal != nil && [JavaUtilCollection_class_() isInstance:persistedDeal]) {
      @try {
        activeAgencies_ = (id<JavaUtilCollection>) check_protocol_cast(persistedDeal, @protocol(JavaUtilCollection));
      }
      @catch (JavaLangException *exception) {
        ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"Error loading persisted file, dropping it");
        [ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ saveObjectWithNSString:ComRemulasceLametroappJava_coreRegionalizationHelper_ACTIVE_REGIONS_ withId:nil];
      }
    }
    else {
      if (installedAgencies_ == nil || [installedAgencies_ size] == 0) {
        ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"No installed agencies, can't properly make default active agencies");
        activeAgencies_ = [[JavaUtilArrayList alloc] init];
        return;
      }
      [((id<JavaUtilCollection>) nil_chk(activeAgencies_)) addAllWithJavaUtilCollection:installedAgencies_];
    }
  }
}

+ (ComRemulasceLametroappJava_coreRegionalizationHelper *)getInstance {
  return ComRemulasceLametroappJava_coreRegionalizationHelper_getInstance();
}

- (void)setAutoDetectWithBoolean:(jboolean)autoDetect {
  self->autoDetect_ = autoDetect;
  [((id<ComRemulasceLametroappComponentsPersistenceFieldSaver>) nil_chk(ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_)) saveObjectWithNSString:ComRemulasceLametroappJava_coreRegionalizationHelper_AUTODETECT_REGIONS_ withId:JavaLangBoolean_valueOfWithBoolean_(autoDetect)];
  if (autoDetect) {
    ComRemulasceLametroappJava_coreRegionalizationHelper_autodetectRegions(self);
  }
}

- (jboolean)getAutoDetect {
  return self->autoDetect_;
}

- (id<JavaUtilCollection>)getInstalledAgencies {
  return installedAgencies_;
}

- (void)setInstalledAgenciesWithJavaUtilCollection:(id<JavaUtilCollection>)agencies {
  self->installedAgencies_ = agencies;
}

- (id<JavaUtilCollection>)getActiveAgencies {
  if (autoDetect_ && JavaLangSystem_currentTimeMillis() > lastRegionUpdateTime_ + 60000) {
    ComRemulasceLametroappJava_coreRegionalizationHelper_autodetectRegions(self);
  }
  return activeAgencies_;
}

- (void)autodetectRegions {
  ComRemulasceLametroappJava_coreRegionalizationHelper_autodetectRegions(self);
}

- (void)setActiveAgenciesWithJavaUtilCollection:(id<JavaUtilCollection>)agencies {
  self->activeAgencies_ = agencies;
  if (ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ != nil) {
    [ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ saveObjectWithNSString:@"active_regions" withId:activeAgencies_];
  }
}

+ (void)initialize {
  if (self == [ComRemulasceLametroappJava_coreRegionalizationHelper class]) {
    ComRemulasceLametroappJava_coreRegionalizationHelper_instance_ = [[ComRemulasceLametroappJava_coreRegionalizationHelper alloc] init];
    J2OBJC_SET_INITIALIZED(ComRemulasceLametroappJava_coreRegionalizationHelper)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setPersistenceWithComRemulasceLametroappComponentsPersistenceFieldSaver:", "setPersistence", "V", 0x9, NULL },
    { "init", "RegionalizationHelper", NULL, 0x2, NULL },
    { "loadPersistedAgencies", NULL, "V", 0x1, NULL },
    { "getInstance", NULL, "Lcom.remulasce.lametroapp.java_core.RegionalizationHelper;", 0x9, NULL },
    { "setAutoDetectWithBoolean:", "setAutoDetect", "V", 0x1, NULL },
    { "getAutoDetect", NULL, "Z", 0x1, NULL },
    { "getInstalledAgencies", NULL, "Ljava.util.Collection;", 0x1, NULL },
    { "setInstalledAgenciesWithJavaUtilCollection:", "setInstalledAgencies", "V", 0x1, NULL },
    { "getActiveAgencies", NULL, "Ljava.util.Collection;", 0x1, NULL },
    { "autodetectRegions", NULL, "V", 0x2, NULL },
    { "setActiveAgenciesWithJavaUtilCollection:", "setActiveAgencies", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "instance_", NULL, 0x1a, "Lcom.remulasce.lametroapp.java_core.RegionalizationHelper;", &ComRemulasceLametroappJava_coreRegionalizationHelper_instance_,  },
    { "ACTIVE_REGIONS_", NULL, 0x19, "Ljava.lang.String;", &ComRemulasceLametroappJava_coreRegionalizationHelper_ACTIVE_REGIONS_,  },
    { "AUTODETECT_REGIONS_", NULL, 0x19, "Ljava.lang.String;", &ComRemulasceLametroappJava_coreRegionalizationHelper_AUTODETECT_REGIONS_,  },
    { "persistence_", NULL, 0xa, "Lcom.remulasce.lametroapp.components.persistence.FieldSaver;", &ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_,  },
    { "TAG_", NULL, 0x1a, "Ljava.lang.String;", &ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_,  },
    { "installedAgencies_", NULL, 0x2, "Ljava.util.Collection;", NULL,  },
    { "activeAgencies_", NULL, 0x2, "Ljava.util.Collection;", NULL,  },
    { "lastRegionUpdateTime_", NULL, 0x2, "J", NULL,  },
    { "autoDetect_", NULL, 0x2, "Z", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreRegionalizationHelper = { 2, "RegionalizationHelper", "com.remulasce.lametroapp.java_core", NULL, 0x1, 11, methods, 9, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreRegionalizationHelper;
}

@end

void ComRemulasceLametroappJava_coreRegionalizationHelper_setPersistenceWithComRemulasceLametroappComponentsPersistenceFieldSaver_(id<ComRemulasceLametroappComponentsPersistenceFieldSaver> persistence) {
  ComRemulasceLametroappJava_coreRegionalizationHelper_init();
  ComRemulasceLametroappJava_coreRegionalizationHelper_persistence_ = persistence;
}

ComRemulasceLametroappJava_coreRegionalizationHelper *ComRemulasceLametroappJava_coreRegionalizationHelper_getInstance() {
  ComRemulasceLametroappJava_coreRegionalizationHelper_init();
  return ComRemulasceLametroappJava_coreRegionalizationHelper_instance_;
}

void ComRemulasceLametroappJava_coreRegionalizationHelper_autodetectRegions(ComRemulasceLametroappJava_coreRegionalizationHelper *self) {
  ComRemulasceLametroappJava_coreBasic_typesBasicLocation *current = [((id<ComRemulasceLametroappJava_coreLocationLocationRetriever>) nil_chk(ComRemulasceLametroappJava_coreLocationGlobalLocationProvider_getRetriever())) getCurrentLocation];
  if (current == nil) {
    ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, @"Couldn't automatically update current region from helper");
    self->lastRegionUpdateTime_ = JavaLangSystem_currentTimeMillis() - 55000;
  }
  else {
    self->lastRegionUpdateTime_ = JavaLangSystem_currentTimeMillis();
    id<JavaUtilCollection> newActiveAgencies = [[JavaUtilArrayList alloc] init];
    for (ComRemulasceLametroappJava_coreBasic_typesAgency * __strong a in nil_chk(self->installedAgencies_)) {
      if ([((ComRemulasceLametroappJava_coreBasic_typesAgency *) nil_chk(a)) hasBounds]) {
        if (current->latitude_ > ((ComRemulasceLametroappJava_coreBasic_typesBasicLocation *) nil_chk(a->minLatLonBound_))->latitude_ && current->latitude_ < ((ComRemulasceLametroappJava_coreBasic_typesBasicLocation *) nil_chk(a->maxLatLonBound_))->latitude_ && current->longitude_ > a->minLatLonBound_->longitude_ && current->longitude_ < a->maxLatLonBound_->longitude_) {
          [newActiveAgencies addWithId:a];
        }
        else {
        }
      }
      else {
        ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, JreStrcat("$@", @"RegionalizationHelper can't regionalize an agency with no bounds: ", a));
      }
    }
    [self setActiveAgenciesWithJavaUtilCollection:newActiveAgencies];
  }
  ComRemulasceLametroappJava_coreAnalyticsLog_dWithNSString_withNSString_(ComRemulasceLametroappJava_coreRegionalizationHelper_TAG_, JreStrcat("$@", @"RegionalizationHelper pulled current location: ", current));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreRegionalizationHelper)
