//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/RegionalizationHelper.java
//

#ifndef _ComRemulasceLametroappJava_coreRegionalizationHelper_H_
#define _ComRemulasceLametroappJava_coreRegionalizationHelper_H_

@protocol JavaUtilCollection;

#include "J2ObjC_header.h"

@interface ComRemulasceLametroappJava_coreRegionalizationHelper : NSObject {
 @public
  NSString *agencyName_;
}

#pragma mark Public

- (id<JavaUtilCollection>)getActiveAgencies;

+ (ComRemulasceLametroappJava_coreRegionalizationHelper *)getInstance;

- (void)setActiveAgenciesWithJavaUtilCollection:(id<JavaUtilCollection>)agencies;

@end

FOUNDATION_EXPORT BOOL ComRemulasceLametroappJava_coreRegionalizationHelper_initialized;
J2OBJC_STATIC_INIT(ComRemulasceLametroappJava_coreRegionalizationHelper)

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreRegionalizationHelper, agencyName_, NSString *)

FOUNDATION_EXPORT ComRemulasceLametroappJava_coreRegionalizationHelper *ComRemulasceLametroappJava_coreRegionalizationHelper_getInstance();

FOUNDATION_EXPORT ComRemulasceLametroappJava_coreRegionalizationHelper *ComRemulasceLametroappJava_coreRegionalizationHelper_instance_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreRegionalizationHelper, instance_, ComRemulasceLametroappJava_coreRegionalizationHelper *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreRegionalizationHelper)

#endif // _ComRemulasceLametroappJava_coreRegionalizationHelper_H_
