//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/RequestStatusTrip.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Log.h"
#include "RequestStatusTrip.h"
#include "StopServiceRequest.h"
#include "java/lang/IllegalArgumentException.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip () {
 @public
  ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *parentRequest_;
  jboolean hidden_;
}
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip, parentRequest_, ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *)

@implementation ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip

- (instancetype)initWithComRemulasceLametroappJava_coreBasic_typesStopServiceRequest:(ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *)parent {
  if (self = [super init]) {
    hidden_ = NO;
    self->parentRequest_ = parent;
  }
  return self;
}

- (NSString *)getTitleText {
  return [((ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *) nil_chk(parentRequest_)) getDisplayName];
}

- (ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum *)getRequestStatus {
  switch ([[((ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *) nil_chk(parentRequest_)) getNetworkStatus] ordinal]) {
    case ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_NetworkStatusState_NOTHING:
    return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_get_NOTHING();
    case ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_NetworkStatusState_SPINNER:
    return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_get_SPINNER();
    case ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_NetworkStatusState_ERROR:
    return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_get_ERROR();
    default:
    ComRemulasceLametroappJava_coreAnalyticsLog_wWithNSString_withNSString_(@"RequestStatusTrip", @"Unknown parent request status");
    return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_get_NOTHING();
  }
}

- (NSString *)getAgencyName {
  return [((ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest *) nil_chk(parentRequest_)) getAgencyName];
}

- (void)dismiss {
  self->hidden_ = YES;
}

- (jboolean)isValid {
  return !self->hidden_;
}

- (void)restore {
  self->hidden_ = NO;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComRemulasceLametroappJava_coreBasic_typesStopServiceRequest:", "RequestStatusTrip", NULL, 0x1, NULL },
    { "getTitleText", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getRequestStatus", NULL, "Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;", 0x1, NULL },
    { "getAgencyName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "dismiss", NULL, "V", 0x1, NULL },
    { "isValid", NULL, "Z", 0x1, NULL },
    { "restore", NULL, "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "parentRequest_", NULL, 0x2, "Lcom.remulasce.lametroapp.java_core.basic_types.StopServiceRequest;", NULL,  },
    { "hidden_", NULL, 0x2, "Z", NULL,  },
  };
  static const char *inner_classes[] = {"Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;"};
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip = { 2, "RequestStatusTrip", "com.remulasce.lametroapp.java_core.dynamic_data.types", NULL, 0x1, 7, methods, 2, fields, 0, NULL, 1, inner_classes};
  return &_ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip)

BOOL ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_initialized = NO;

ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum *ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_values_[3];

@implementation ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

IOSObjectArray *ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_values() {
  ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_init();
  return [IOSObjectArray arrayWithObjects:ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_values_ count:3 type:ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_class_()];
}
+ (IOSObjectArray *)values {
  return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_values();
}

+ (ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum *)valueOfWithNSString:(NSString *)name {
  return ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_valueOfWithNSString_(name);
}

ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum *ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_valueOfWithNSString_(NSString *name) {
  ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_init();
  for (int i = 0; i < 3; i++) {
    ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum *e = ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum class]) {
    ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_NOTHING = [[ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum alloc] initWithNSString:@"NOTHING" withInt:0];
    ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_SPINNER = [[ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum alloc] initWithNSString:@"SPINNER" withInt:1];
    ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_ERROR = [[ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum alloc] initWithNSString:@"ERROR" withInt:2];
    J2OBJC_SET_INITIALIZED(ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "init", NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NOTHING", "NOTHING", 0x4019, "Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;", &ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_NOTHING,  },
    { "SPINNER", "SPINNER", 0x4019, "Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;", &ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_SPINNER,  },
    { "ERROR", "ERROR", 0x4019, "Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;", &ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum_ERROR,  },
  };
  static const char *superclass_type_args[] = {"Lcom.remulasce.lametroapp.java_core.dynamic_data.types.RequestStatusTrip$RequestDisplayType;"};
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum = { 2, "RequestDisplayType", "com.remulasce.lametroapp.java_core.dynamic_data.types", "RequestStatusTrip", 0x4019, 1, methods, 3, fields, 1, superclass_type_args, 0, NULL};
  return &_ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreDynamic_dataTypesRequestStatusTrip_RequestDisplayTypeEnum)
