//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/types/RouteColor.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "RouteColor.h"

@implementation ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor

- (instancetype)initWithNSString:(NSString *)color {
  if (self = [super init]) {
    self->color_ = color;
  }
  return self;
}

- (jboolean)isEqual:(id)o {
  if (self == o) return YES;
  if (o == nil || [self getClass] != [o getClass]) return NO;
  ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *that = (ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *) check_class_cast(o, [ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor class]);
  return !(color_ != nil ? ![color_ isEqual:((ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *) nil_chk(that))->color_] : ((ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *) nil_chk(that))->color_ != nil);
}

- (NSUInteger)hash {
  return color_ != nil ? ((jint) [color_ hash]) : 0;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "RouteColor", NULL, 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "color_", NULL, 0x1, "Ljava.lang.String;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor = { 2, "RouteColor", "com.remulasce.lametroapp.java_core.static_data.types", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor)
