//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/RouteColorer.java
//

#include "J2ObjC_source.h"
#include "Route.h"
#include "RouteColor.h"
#include "RouteColorer.h"

@interface ComRemulasceLametroappJava_coreStatic_dataRouteColorer : NSObject
@end

@implementation ComRemulasceLametroappJava_coreStatic_dataRouteColorer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getColorWithComRemulasceLametroappJava_coreBasic_typesRoute:", "getColor", "Lcom.remulasce.lametroapp.java_core.static_data.types.RouteColor;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreStatic_dataRouteColorer = { 2, "RouteColorer", "com.remulasce.lametroapp.java_core.static_data", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreStatic_dataRouteColorer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreStatic_dataRouteColorer)
