//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/RouteColorer.java
//

#ifndef _ComRemulasceLametroappJava_coreStatic_dataRouteColorer_H_
#define _ComRemulasceLametroappJava_coreStatic_dataRouteColorer_H_

@class ComRemulasceLametroappJava_coreBasic_typesRoute;
@class ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor;

#include "J2ObjC_header.h"

@protocol ComRemulasceLametroappJava_coreStatic_dataRouteColorer < NSObject, JavaObject >

#pragma mark Public

- (ComRemulasceLametroappJava_coreStatic_dataTypesRouteColor *)getColorWithComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)r;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreStatic_dataRouteColorer)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreStatic_dataRouteColorer)

#endif // _ComRemulasceLametroappJava_coreStatic_dataRouteColorer_H_
