//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/Stop.java
//

#include "Agency.h"
#include "BasicLocation.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LaMetroUtil.h"
#include "Stop.h"
#include "android/util/Log.h"
#include "java/lang/Integer.h"

@interface ComRemulasceLametroappJava_coreBasic_typesStop () {
 @public
  NSString *raw_;
  NSString *stopName_;
  ComRemulasceLametroappJava_coreBasic_typesAgency *agency_;
  ComRemulasceLametroappJava_coreBasic_typesBasicLocation *location_;
}
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesStop, raw_, NSString *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesStop, stopName_, NSString *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesStop, agency_, ComRemulasceLametroappJava_coreBasic_typesAgency *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreBasic_typesStop, location_, ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)

@implementation ComRemulasceLametroappJava_coreBasic_typesStop

- (instancetype)init {
  if (self = [super init]) {
    raw_ = @"";
    stopName_ = @"";
    agency_ = nil;
  }
  return self;
}

- (instancetype)initWithNSString:(NSString *)stopText {
  if (self = [super init]) {
    raw_ = @"";
    stopName_ = @"";
    agency_ = nil;
    raw_ = stopText;
  }
  return self;
}

- (instancetype)initWithInt:(jint)stopNum {
  if (self = [super init]) {
    raw_ = @"";
    stopName_ = @"";
    agency_ = nil;
    raw_ = NSString_valueOfInt_(stopNum);
  }
  return self;
}

- (jboolean)isValid {
  return ComRemulasceLametroappJava_coreLaMetroUtil_isValidStopWithNSString_(raw_);
}

- (jint)getNum {
  return [JavaLangInteger_valueOfWithNSString_(raw_) intValue];
}

- (NSString *)getStopID {
  return raw_;
}

- (void)setStopIDWithNSString:(NSString *)stopID {
  raw_ = stopID;
}

- (void)setAgencyWithComRemulasceLametroappJava_coreBasic_typesAgency:(ComRemulasceLametroappJava_coreBasic_typesAgency *)agency {
  self->agency_ = agency;
}

- (ComRemulasceLametroappJava_coreBasic_typesAgency *)getAgency {
  return agency_;
}

- (NSString *)getString {
  return raw_;
}

- (void)setStopNameWithNSString:(NSString *)stopName {
  if (stopName != nil && ![stopName isEmpty]) {
    self->stopName_ = stopName;
  }
  else {
    AndroidUtilLog_wWithNSString_withNSString_(@"Stop", @"Bad stopname ignored");
  }
}

- (NSString *)getStopName {
  if ([((NSString *) nil_chk(stopName_)) isEmpty]) {
    return [self getString];
  }
  else {
    return stopName_;
  }
}

- (void)setLocationWithComRemulasceLametroappJava_coreBasic_typesBasicLocation:(ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)location {
  self->location_ = location;
}

- (ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)getLocation {
  return location_;
}

- (NSUInteger)hash {
  return ((jint) [((NSString *) nil_chk(raw_)) hash]);
}

- (jboolean)isEqual:(id)o {
  if ([nil_chk(o) getClass] != [self getClass]) {
    return NO;
  }
  return ((jint) [o hash]) == ((jint) [self hash]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Stop", NULL, 0x1, NULL },
    { "initWithNSString:", "Stop", NULL, 0x1, NULL },
    { "initWithInt:", "Stop", NULL, 0x1, NULL },
    { "isValid", NULL, "Z", 0x1, NULL },
    { "getNum", NULL, "I", 0x1, NULL },
    { "getStopID", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setStopIDWithNSString:", "setStopID", "V", 0x1, NULL },
    { "setAgencyWithComRemulasceLametroappJava_coreBasic_typesAgency:", "setAgency", "V", 0x1, NULL },
    { "getAgency", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.Agency;", 0x1, NULL },
    { "getString", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setStopNameWithNSString:", "setStopName", "V", 0x1, NULL },
    { "getStopName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setLocationWithComRemulasceLametroappJava_coreBasic_typesBasicLocation:", "setLocation", "V", 0x1, NULL },
    { "getLocation", NULL, "Lcom.remulasce.lametroapp.java_core.basic_types.BasicLocation;", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, .constantValue.asLong = ComRemulasceLametroappJava_coreBasic_typesStop_serialVersionUID },
    { "raw_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "stopName_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "agency_", NULL, 0x2, "Lcom.remulasce.lametroapp.java_core.basic_types.Agency;", NULL,  },
    { "location_", NULL, 0x2, "Lcom.remulasce.lametroapp.java_core.basic_types.BasicLocation;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreBasic_typesStop = { 2, "Stop", "com.remulasce.lametroapp.java_core.basic_types", NULL, 0x1, 16, methods, 5, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreBasic_typesStop;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreBasic_typesStop)
