//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/StopNameTranslator.java
//

#ifndef _ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator_H_
#define _ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator_H_

@protocol JavaUtilCollection;

#include "J2ObjC_header.h"

@protocol ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator < NSObject, JavaObject >

#pragma mark Package-Private

- (id<JavaUtilCollection>)getStopIDWithNSString:(NSString *)stopName;

- (NSString *)getStopNameWithNSString:(NSString *)stopID;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator)

#endif // _ComRemulasceLametroappJava_coreStatic_dataStopNameTranslator_H_
