//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/StopLocationTranslator.java
//

#ifndef _ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator_H_
#define _ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator_H_

@class ComRemulasceLametroappJava_coreBasic_typesBasicLocation;
@class ComRemulasceLametroappJava_coreBasic_typesStop;

#include "J2ObjC_header.h"

@protocol ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator < NSObject, JavaObject >

#pragma mark Public

- (ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)getStopLocationWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator)

#endif // _ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator_H_
