//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/StopServiceRequest.java
//

#ifndef _ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_H_
#define _ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_H_

@class ComRemulasceLametroappJava_coreBasic_typesStop;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol JavaUtilCollection;

#include "J2ObjC_header.h"
#include "ServiceRequest.h"

@interface ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest : ComRemulasceLametroappJava_coreBasic_typesServiceRequest {
}

#pragma mark Public

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)stops
                              withNSString:(NSString *)displayName;

- (instancetype)initWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop
                                                          withNSString:(NSString *)displayName;

- (void)cancelRequest;

- (id<JavaUtilCollection>)getRaw;

- (id<JavaUtilCollection>)getTrips;

- (jboolean)hasTripsToDisplay;

- (jboolean)isValid;

- (void)pauseRequest;

- (void)restoreTrips;

- (void)resumeRequest;

- (void)startRequest;

- (jboolean)updateAvailable;

- (void)updateTaken;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest, TAG_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest)

#endif // _ComRemulasceLametroappJava_coreBasic_typesStopServiceRequest_H_
