//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/StopRouteDestinationArrival.java
//

#ifndef _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_H_
#define _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_H_

@class ComRemulasceLametroappJava_coreBasic_typesDestination;
@class ComRemulasceLametroappJava_coreBasic_typesRoute;
@class ComRemulasceLametroappJava_coreBasic_typesStop;
@class ComRemulasceLametroappJava_coreDynamic_dataTypesTrip;
@protocol JavaUtilCollection;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/util/Comparator.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival : NSObject < JavaIoSerializable > {
 @public
  ComRemulasceLametroappJava_coreBasic_typesStop *stop_;
  ComRemulasceLametroappJava_coreBasic_typesRoute *route_;
  ComRemulasceLametroappJava_coreBasic_typesDestination *destination_;
}

#pragma mark Public

- (instancetype)initWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)s
                   withComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)r
             withComRemulasceLametroappJava_coreBasic_typesDestination:(ComRemulasceLametroappJava_coreBasic_typesDestination *)d;

- (id<JavaUtilCollection>)getArrivals;

- (ComRemulasceLametroappJava_coreBasic_typesDestination *)getDirection;

- (jfloat)getRequestedUpdateInterval;

- (ComRemulasceLametroappJava_coreBasic_typesRoute *)getRoute;

- (ComRemulasceLametroappJava_coreBasic_typesStop *)getStop;

- (ComRemulasceLametroappJava_coreDynamic_dataTypesTrip *)getTrip;

- (jboolean)isInScope;

- (void)setScopeWithBoolean:(jboolean)inScope;

- (void)updateArrivalTimesWithJavaUtilCollection:(id<JavaUtilCollection>)updatedArrivals;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival)

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival, stop_, ComRemulasceLametroappJava_coreBasic_typesStop *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival, route_, ComRemulasceLametroappJava_coreBasic_typesRoute *)
J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival, destination_, ComRemulasceLametroappJava_coreBasic_typesDestination *)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival, TAG_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival)

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_$1 : NSObject < JavaUtilComparator > {
}

#pragma mark Public

- (jint)compareWithId:(id)o
               withId:(id)o2;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_$1)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_$1)

#endif // _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationArrival_H_
