//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/Stop.java
//

#ifndef _ComRemulasceLametroappJava_coreBasic_typesStop_H_
#define _ComRemulasceLametroappJava_coreBasic_typesStop_H_

@class ComRemulasceLametroappJava_coreBasic_typesBasicLocation;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

#define ComRemulasceLametroappJava_coreBasic_typesStop_serialVersionUID 4336735625715608793LL

@interface ComRemulasceLametroappJava_coreBasic_typesStop : NSObject < JavaIoSerializable > {
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)stopNum;

- (instancetype)initWithNSString:(NSString *)stopText;

- (jboolean)isEqual:(id)o;

- (ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)getLocation;

- (jint)getNum;

- (NSString *)getStopID;

- (NSString *)getStopName;

- (NSString *)getString;

- (NSUInteger)hash;

- (jboolean)isValid;

- (void)setLocationWithComRemulasceLametroappJava_coreBasic_typesBasicLocation:(ComRemulasceLametroappJava_coreBasic_typesBasicLocation *)location;

- (void)setStopNameWithNSString:(NSString *)stopName;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreBasic_typesStop)

J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreBasic_typesStop, serialVersionUID, jlong)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreBasic_typesStop)

#endif // _ComRemulasceLametroappJava_coreBasic_typesStop_H_
