//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/app/src/main/java/com/remulasce/lametroapp/java_core/static_data/StopLocationTranslator.java
//

#include "BasicLocation.h"
#include "J2ObjC_source.h"
#include "Stop.h"
#include "StopLocationTranslator.h"

@interface ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator : NSObject
@end

@implementation ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getStopLocationWithComRemulasceLametroappJava_coreBasic_typesStop:", "getStopLocation", "Lcom.remulasce.lametroapp.java_core.basic_types.BasicLocation;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator = { 2, "StopLocationTranslator", "com.remulasce.lametroapp.java_core.static_data", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreStatic_dataStopLocationTranslator)
