//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/StopRouteDestinationPrediction.java
//

#ifndef _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction_H_
#define _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction_H_

@class ComRemulasceLametroappJava_coreBasic_typesRoute;
@class ComRemulasceLametroappJava_coreBasic_typesStop;
@class ComRemulasceLametroappJava_coreDynamic_dataTypesArrival;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol JavaUtilCollection;

#include "J2ObjC_header.h"
#include "Prediction.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction : ComRemulasceLametroappJava_coreDynamic_dataTypesPrediction {
}

#pragma mark Public

- (instancetype)initWithComRemulasceLametroappJava_coreBasic_typesStop:(ComRemulasceLametroappJava_coreBasic_typesStop *)stop
                   withComRemulasceLametroappJava_coreBasic_typesRoute:(ComRemulasceLametroappJava_coreBasic_typesRoute *)route;

- (void)cancelTrips;

- (id<JavaUtilCollection>)getArrivals;

- (jint)getRequestedUpdateInterval;

- (NSString *)getRequestString;

- (ComRemulasceLametroappJava_coreBasic_typesRoute *)getRoute;

- (ComRemulasceLametroappJava_coreBasic_typesStop *)getStop;

- (jlong)getTimeSinceLastUpdate;

- (void)handleResponseWithNSString:(NSString *)response;

- (jboolean)hasAnyPredictions;

- (NSUInteger)hash;

- (void)restoreTrips;

- (void)startPredicting;

- (void)stopPredicting;

#pragma mark Package-Private

- (jboolean)arrivalTrackedWithComRemulasceLametroappJava_coreDynamic_dataTypesArrival:(ComRemulasceLametroappJava_coreDynamic_dataTypesArrival *)a;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction)

FOUNDATION_EXPORT NSString *ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction, TAG_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction)

#endif // _ComRemulasceLametroappJava_coreDynamic_dataTypesStopRouteDestinationPrediction_H_
