//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/MetroAppIOS/MetroApp/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/Trip.java
//

#include "J2ObjC_source.h"
#include "Trip.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesTrip () {
 @public
  NSString *text_;
}
@end

J2OBJC_FIELD_SETTER(ComRemulasceLametroappJava_coreDynamic_dataTypesTrip, text_, NSString *)

@implementation ComRemulasceLametroappJava_coreDynamic_dataTypesTrip

- (NSString *)getInfo {
  return [self description];
}

- (void)setTextWithNSString:(NSString *)text {
  self->text_ = text;
}

- (NSString *)description {
  return text_;
}

- (jfloat)getPriority {
  return 50;
}

- (jboolean)isValid {
  return YES;
}

- (void)dismiss {
}

- (instancetype)init {
  if (self = [super init]) {
    text_ = @"...";
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getInfo", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setTextWithNSString:", "setText", "V", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
    { "getPriority", NULL, "F", 0x1, NULL },
    { "isValid", NULL, "Z", 0x1, NULL },
    { "dismiss", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "text_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static const J2ObjcClassInfo _ComRemulasceLametroappJava_coreDynamic_dataTypesTrip = { 2, "Trip", "com.remulasce.lametroapp.java_core.dynamic_data.types", NULL, 0x1, 7, methods, 1, fields, 0, NULL, 0, NULL};
  return &_ComRemulasceLametroappJava_coreDynamic_dataTypesTrip;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComRemulasceLametroappJava_coreDynamic_dataTypesTrip)
