//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/dynamic_data/types/Trip.java
//

#ifndef _ComRemulasceLametroappJava_coreDynamic_dataTypesTrip_H_
#define _ComRemulasceLametroappJava_coreDynamic_dataTypesTrip_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface ComRemulasceLametroappJava_coreDynamic_dataTypesTrip : NSObject < JavaIoSerializable > {
}

#pragma mark Public

- (instancetype)init;

- (void)dismiss;

- (NSString *)getInfo;

- (jfloat)getPriority;

- (jboolean)isValid;

- (void)setTextWithNSString:(NSString *)text;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreDynamic_dataTypesTrip)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreDynamic_dataTypesTrip)

#endif // _ComRemulasceLametroappJava_coreDynamic_dataTypesTrip_H_
