//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nighelles/Desktop/metroapp/app/src/main/java/com/remulasce/lametroapp/java_core/basic_types/Vehicle.java
//

#ifndef _ComRemulasceLametroappJava_coreBasic_typesVehicle_H_
#define _ComRemulasceLametroappJava_coreBasic_typesVehicle_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

#define ComRemulasceLametroappJava_coreBasic_typesVehicle_serialVersionUID 8262057532533371341LL

@interface ComRemulasceLametroappJava_coreBasic_typesVehicle : NSObject < JavaIoSerializable > {
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)veh;

- (jboolean)isEqual:(id)o;

- (NSString *)getString;

- (NSUInteger)hash;

- (jboolean)isValid;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRemulasceLametroappJava_coreBasic_typesVehicle)

J2OBJC_STATIC_FIELD_GETTER(ComRemulasceLametroappJava_coreBasic_typesVehicle, serialVersionUID, jlong)

J2OBJC_TYPE_LITERAL_HEADER(ComRemulasceLametroappJava_coreBasic_typesVehicle)

#endif // _ComRemulasceLametroappJava_coreBasic_typesVehicle_H_
